{% set name = "mlrose-ky" %}
{% set version = "1.1.6" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/mlrose_ky-{{ version }}.tar.gz
  sha256: 50a7e2fec9ca6c64418809185acf96aa220d4c62ae8d67519a30bd281dcc7758

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools
  run:
    - python >=3.10
    - joblib
    - matplotlib-base
    - networkx
    - numpy
    - pandas
    - scikit-learn
    - scipy

test:
  imports:
    - mlrose_ky
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/knakamura13/mlrose-ky
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "MLROSe-ky: Machine Learning, Randomized Optimization and Search"
  description: |
    MLROSe-ky is a Python package for applying common randomized optimization and search algorithms to various optimization problems over both discrete and continuous parameter spaces.
  dev_url: https://github.com/knakamura13/mlrose-ky

extra:
  recipe-maintainers:
    - knakamura13
